name: note2note
dependencies:
  - python=3.11
  - pip
  - pip:
    - asttokens==3.0.0
    - certifi==2024.12.14
    - charset-normalizer==3.4.1
    - contourpy==1.3.1
    - cycler==0.12.1
    - decorator==5.1.1
    - executing==2.2.0
    - filelock==3.17.0
    - fonttools==4.55.5
    - fsspec==2024.12.0
    - huggingface-hub==0.27.1
    - idna==3.10
    - ipython==8.31.0
    - jedi==0.19.2
    - Jinja2==3.1.5
    - kiwisolver==1.4.8
    - MarkupSafe==3.0.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.7
    - midi2audio==0.1.1
    - mido==1.2.10
    - mpmath==1.3.0
    - music21
    - networkx==3.4.2
    - numpy==1.26.4
    - packaging==24.2
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==11.1.0
    - prompt_toolkit==3.0.50
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - pretty_midi
    - Pygments==2.19.1
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - PyYAML==6.0.2
    - python-osc
    - regex==2024.11.6
    - requests==2.32.3
    - safetensors==0.5.2
    - scipy==1.15.1
    - six==1.17.0
    - stack-data==0.6.3
    - sympy==1.13.3
    - tokenizers==0.21.0
    - torch==2.2.2
    - tqdm==4.65.0
    - traitlets==5.14.3
    - transformers==4.48.1
    - typing_extensions==4.12.2
    - urllib3==2.3.0
    - watchdog==6.0.0
    - wcwidth==0.2.13
    - anticipation @ file:///Users/music/RyanBaker/GuitarBot-Jams/note2anticipation/anticipation
